version: '3'
services:
    server:
        build: .
        container_name: fuquizserver
        image: dauleduc2/fuquizserver:latest
        ports:
            - 4000:4000
        networks:
            - tetcha
networks:
    tetcha:
        external: true
