version: '3'
services:
    db:
        container_name: mysql
        image: mysql:8.0.26
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: fu_quiz
            MYSQL_ROOT_PASSWORD: 123456
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./data/mysql:/var/lib/mysql
